# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-06 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermessage',
            table='usermessage',
        ),
    ]
